from __future__ import annotations

import argparse
import os
from pathlib import Path
import signal
import socket
import subprocess
import sys
import time
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV_FILE = REPO_ROOT / 'deploy' / 'no_docker' / '.env.local'
DEFAULT_OPENAI_KEY_FILE = Path(r'C:\Users\Kushals.DESKTOP-D51MT8S\Downloads\IRIS\Key\OPEN AI API Key.txt')
DEFAULT_GOOGLE_KEY_FILE = Path(r'C:\Users\Kushals.DESKTOP-D51MT8S\Downloads\IRIS\Key\Google Cloud Key.txt')
LOG_DIR = REPO_ROOT / 'deploy' / 'no_docker' / 'runtime_logs'
PID_DIR = LOG_DIR / 'pids'

WINDOWS_CREATE_FLAGS = 0
if os.name == 'nt':
    WINDOWS_CREATE_FLAGS = subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.DETACHED_PROCESS

SERVICES = {
    'web': {
        'script': REPO_ROOT / 'scripts' / 'start_web_app.py',
        'stdout': LOG_DIR / 'web.out.log',
        'stderr': LOG_DIR / 'web.err.log',
        'pid': PID_DIR / 'web.pid',
    },
    'scheduler': {
        'script': REPO_ROOT / 'scripts' / 'start_scheduler_worker_service.py',
        'stdout': LOG_DIR / 'scheduler.out.log',
        'stderr': LOG_DIR / 'scheduler.err.log',
        'pid': PID_DIR / 'scheduler.pid',
    },
    'onfly_scheduler': {
        'script': REPO_ROOT / 'scripts' / 'start_onfly_scheduler_service.py',
        'stdout': LOG_DIR / 'onfly.out.log',
        'stderr': LOG_DIR / 'onfly.err.log',
        'pid': PID_DIR / 'onfly.pid',
    },
}


def _python_executable() -> Path:
    candidates = [
        REPO_ROOT / '.venv' / 'Scripts' / 'python.exe',
        REPO_ROOT / '.venv' / 'bin' / 'python',
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return Path(sys.executable)


def _read_key_file(path: Path) -> str:
    if not path.exists():
        return ''
    return path.read_text(encoding='utf-8').strip()


def _compose_local_env(repo_root: Path, openai_key: str, google_key: str) -> str:
    data_dir = (repo_root / 'data').resolve()
    app_dir = repo_root.resolve()
    lines = [
        '# Auto-generated by scripts/local_runtime_manager.py',
        f'IRIS_APP_DIR={app_dir}',
        f'IRIS_DATA_DIR={data_dir}',
        f'IRIS_DB_PATH={(data_dir / "store_registry.db").resolve()}',
        f'IRIS_STORES_ROOT={(data_dir / "stores").resolve()}',
        f'IRIS_EXPORT_DIR={(data_dir / "exports" / "current").resolve()}',
        f'IRIS_EMPLOYEE_ASSETS_DIR={(data_dir / "employee_assets").resolve()}',
        'IRIS_STREAMLIT_HOST=0.0.0.0',
        'IRIS_STREAMLIT_PORT=8765',
        'STREAMLIT_SERVER_HEADLESS=true',
        f'GOOGLE_API_KEY={google_key}',
        f'OPENAI_API_KEY={openai_key}',
        'OPENAI_VISION_MODEL=gpt-4.1-mini',
        'OPENAI_MODEL=gpt-4.1-mini',
        'IRIS_SCHEDULER_POLL_SECONDS=10',
        'IRIS_ONFLY_POLL_SECONDS=30',
        'IRIS_PRELOAD_TORCH=1',
        'IRIS_ALLOW_MOCK_DETECTOR=0',
        'IRIS_FEEDBACK_OVERRIDE_ENABLED=1',
    ]
    return '\n'.join(lines) + '\n'


def ensure_env_file(env_file: Path = DEFAULT_ENV_FILE) -> Path:
    env_file.parent.mkdir(parents=True, exist_ok=True)
    if env_file.exists():
        return env_file
    openai_key = _read_key_file(DEFAULT_OPENAI_KEY_FILE)
    google_key = _read_key_file(DEFAULT_GOOGLE_KEY_FILE)
    if not openai_key:
        raise RuntimeError(f'OpenAI key file missing/empty: {DEFAULT_OPENAI_KEY_FILE}')
    if not google_key:
        raise RuntimeError(f'Google key file missing/empty: {DEFAULT_GOOGLE_KEY_FILE}')
    env_file.write_text(_compose_local_env(REPO_ROOT, openai_key, google_key), encoding='utf-8')
    return env_file


def _load_simple_env(env_file: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    for line in env_file.read_text(encoding='utf-8').splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#') or '=' not in stripped:
            continue
        key, value = stripped.split('=', 1)
        env[key.strip()] = value.strip().strip('"').strip("'")
    return env


def _is_pid_running(pid: int) -> bool:
    if pid <= 0:
        return False
    try:
        if os.name == 'nt':
            completed = subprocess.run(['tasklist', '/FI', f'PID eq {pid}'], capture_output=True, text=True, timeout=10)
            return str(pid) in completed.stdout
        os.kill(pid, 0)
        return True
    except Exception:
        return False


def _read_pid(path: Path) -> int | None:
    try:
        return int(path.read_text(encoding='utf-8').strip())
    except Exception:
        return None


def _write_pid(path: Path, pid: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(str(pid), encoding='utf-8')


def _port_open(host: str, port: int, timeout: float = 1.0) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def _service_status(name: str) -> dict[str, Any]:
    meta = SERVICES[name]
    pid = _read_pid(meta['pid'])
    running = _is_pid_running(pid or -1) if pid is not None else False
    return {'name': name, 'pid': pid or 0, 'running': running, 'stdout': str(meta['stdout']), 'stderr': str(meta['stderr'])}


def start_service(name: str, env_file: Path) -> dict[str, Any]:
    meta = SERVICES[name]
    status = _service_status(name)
    if status['running']:
        return status
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    PID_DIR.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env['IRIS_ENV_FILE'] = str(env_file)
    env.update(_load_simple_env(env_file))
    python_exe = _python_executable()
    stdout = open(meta['stdout'], 'a', encoding='utf-8')
    stderr = open(meta['stderr'], 'a', encoding='utf-8')
    creationflags = WINDOWS_CREATE_FLAGS if os.name == 'nt' else 0
    popen_kwargs: dict[str, Any] = {
        'cwd': str(REPO_ROOT),
        'env': env,
        'stdout': stdout,
        'stderr': stderr,
        'stdin': subprocess.DEVNULL,
    }
    if os.name == 'nt':
        popen_kwargs['creationflags'] = creationflags
    else:
        popen_kwargs['start_new_session'] = True
    proc = subprocess.Popen([str(python_exe), str(meta['script'])], **popen_kwargs)
    _write_pid(meta['pid'], proc.pid)
    return _service_status(name)


def stop_service(name: str) -> dict[str, Any]:
    meta = SERVICES[name]
    pid = _read_pid(meta['pid'])
    if pid and _is_pid_running(pid):
        try:
            if os.name == 'nt':
                subprocess.run(['taskkill', '/PID', str(pid), '/T', '/F'], check=False, capture_output=True, text=True, timeout=15)
            else:
                os.kill(pid, signal.SIGTERM)
        except Exception:
            pass
    try:
        meta['pid'].unlink(missing_ok=True)
    except Exception:
        pass
    return _service_status(name)


def wait_for_web(host: str = '127.0.0.1', port: int = 8765, timeout_seconds: int = 45) -> bool:
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if _port_open(host, port, timeout=1.0):
            return True
        time.sleep(1)
    return False


def print_status(env_file: Path) -> int:
    loaded = _load_simple_env(env_file) if env_file.exists() else {}
    port = int(str(loaded.get('IRIS_STREAMLIT_PORT', '8765') or '8765'))
    web_up = _port_open('127.0.0.1', port, 1.0)
    print(f'IRIS env file: {env_file}')
    print(f'Web URL: http://localhost:{port}')
    for name in SERVICES:
        status = _service_status(name)
        state = 'RUNNING' if status['running'] else 'STOPPED'
        if name == 'web' and (not status['running']) and web_up:
            state = 'UP (external runtime)'
        print(f"- {name}: {state} | pid={status['pid']} | out={status['stdout']}")
    print(f"- web_health: {'UP' if web_up else 'DOWN'}")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Local IRIS no-PowerShell runtime manager')
    parser.add_argument('command', choices=['setup-env', 'start', 'stop', 'restart', 'status', 'open'])
    parser.add_argument('--service', choices=['all', 'web', 'scheduler', 'onfly_scheduler'], default='all')
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    env_file = ensure_env_file()
    services = list(SERVICES.keys()) if args.service == 'all' else [args.service]

    if args.command == 'setup-env':
        print(f'[IRIS] Local env ready: {env_file}')
        return 0
    if args.command == 'status':
        return print_status(env_file)
    if args.command == 'stop':
        for name in reversed(services):
            status = stop_service(name)
            print(f"[IRIS] Stopped {name}: running={status['running']}")
        return 0
    if args.command == 'restart':
        for name in reversed(services):
            stop_service(name)
        time.sleep(1)
        for name in services:
            status = start_service(name, env_file)
            print(f"[IRIS] Started {name}: pid={status['pid']}")
        if 'web' in services or args.service == 'all':
            ok = wait_for_web(timeout_seconds=45)
            print(f"[IRIS] Web health: {'UP' if ok else 'DOWN'}")
        return 0
    if args.command == 'start':
        for name in services:
            status = start_service(name, env_file)
            print(f"[IRIS] Started {name}: pid={status['pid']}")
        if 'web' in services or args.service == 'all':
            ok = wait_for_web(timeout_seconds=45)
            print(f"[IRIS] Web health: {'UP' if ok else 'DOWN'}")
        return 0
    if args.command == 'open':
        loaded = _load_simple_env(env_file)
        port = int(str(loaded.get('IRIS_STREAMLIT_PORT', '8765') or '8765'))
        url = f'http://localhost:{port}'
        os.startfile(url)  # type: ignore[attr-defined]
        print(f'[IRIS] Opened {url}')
        return 0
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
