$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoPath = "C:\Users\Kushals.DESKTOP-D51MT8S\Desktop\Github\IRIS"
$openAiKeyPath = "C:\Users\Kushals.DESKTOP-D51MT8S\Downloads\IRIS\Key\OPEN AI API Key.txt"
$googleKeyPath = "C:\Users\Kushals.DESKTOP-D51MT8S\Downloads\IRIS\Key\Google Cloud Key.txt"
$outEnvPath = Join-Path $repoPath ".env.local"

function Read-SecretFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Name
    )
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "$Name key file not found: $Path"
    }
    $value = (Get-Content -LiteralPath $Path -Raw -ErrorAction Stop).Trim()
    if ([string]::IsNullOrWhiteSpace($value)) {
        throw "$Name key file is empty: $Path"
    }
    return $value
}

if (-not (Test-Path -LiteralPath $repoPath)) {
    throw "Repo path not found: $repoPath"
}

$openAiKey = Read-SecretFile -Path $openAiKeyPath -Name "OPENAI"
$googleKey = Read-SecretFile -Path $googleKeyPath -Name "GOOGLE"

$content = @(
    "# Auto-generated by scripts/setup_local_env.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")"
    "MAX_FRAMES_PER_JOB=100"
    "OPENAI_API_KEY=$openAiKey"
    "OPENAI_VISION_MODEL=gpt-4.1-mini"
    "OPENAI_MODEL=gpt-4.1-mini"
    "GOOGLE_API_KEY=$googleKey"
    "GOOGLE_SERVICE_ACCOUNT_EMAIL=iris-162@iris-490608.iam.gserviceaccount.com"
    "GOOGLE_SERVICE_ACCOUNT_ID=118021309561608766860"
    "GOOGLE_PRIVATE_KEY=replace_with_private_key_from_it_admin"
    "ONFLY_STORE_ID=TEST_STORE_D07"
    "ONFLY_SOURCE_URL=https://drive.google.com/drive/folders/1Wd8X8t-wF_HhPQPYuuFHjqTq6Ojc3Nnw"
    "ONFLY_MAX_IMAGES=100"
    "ONFLY_DETECTOR=yolo"
    "ONFLY_CONF=0.18"
) -join "`n"

Set-Content -LiteralPath $outEnvPath -Value $content -Encoding UTF8
Write-Host "[IRIS] Wrote local env file: $outEnvPath"
Write-Host "[IRIS] Keys loaded from local key files. .env.local is git-ignored."
